name: 'Visual Regression'
description: 'Check visual regressions after a release'
author: 'boaz@tabnine.com'
inputs:
  githubToken:
    required: true
    description: 'Github token - use secrets.GITHUB_TOKEN'
  slackWebhook:
    required: true
    description: 'Slack webhook'
  url:
    required: true
    description: 'Url of the site to take a screenshot of'
  screenshotFilename:
    required: false
    description: 'Name of the screenshot file'
runs:
  using: 'node12'
  main: 'dist/index.js'
