name: Validate Action Works

on:
  release:
    types: [released]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          url: https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode
          slackWebhook: ${{ secrets.SLACK_WEBHOOK }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
